name: RadioBeacon
main: me.kieranwallbanks.radiobeacon.RadioBeacon
version: 1.3
description: build radio towers, navigate to them using compasses
url: http://dev.bukkit.org/server-mods/radiobeacon/
commands: 
    antennas:
        description: Show all antennas
        usage: /antennas
    toggleradio:
        description: Turn your portable compass radio on or off
        usage: /toggleradio
permissions:
    radiobeacon.*:
        children:
            radiobeacon.create: true
            radiobeacon.addmessage: true
            radiobeacon.reveal: true
            radiobeacon.admin: true
        default: false
    radiobeacon.create:
        description: Allows you to build new radio beacon antenna towers
        default: true
    radiobeacon.addmessage:
        description: Allows you to add messages to towers by placing signs
        default: true
    radiobeacon.reveal:
        description: Allows you to list the coordinates of all antennas
        default: op
    radiobeacon.admin:
        description: Allows you to save/load/check antennas
        default: op
